name: 'Set AssemblyInfo Version'
description: 'Sets the assembly version number in the specified assembly info file(s)'
branding:
  icon: 'tag'
  color: 'orange'
inputs:
  version:
    description: 'version to set'
    required: true
  directory:
    description: 'Directory where assembly info file is located'
    default: '.\'
  filename:
    description: 'Filename for assembly info'
    default: 'AssemblyInfo.cs'
  recursive:
    description: 'If `true`, update all assembly info files including in files in subdirectories'
    default: 'true'
  copyright:
    description: 'Copyright to set'
    default: ''
runs:
  using: composite
  steps:
    - shell: pwsh
      id: setversion
      env:
        VERSION:  ${{ inputs.version }}
        DIRECTORY:  ${{ inputs.directory }}
        FILENAME: ${{ inputs.filename }}
        RECURSIVE:  ${{ inputs.recursive }}
        COPYRIGHT:  ${{ inputs.copyright }}
      run: ${{ github.action_path }}\SetVersion.ps1
outputs:
  assembly_version:
    description: Version set in AssemblyVersion
    value: ${{steps.setversion.outputs.assemblyVersion}}
  assembly_file_version:
    description: Version set in AssemblyFileVersion
    value: ${{steps.setversion.outputs.assemblyFileVersion}}
    